### ISSUE TITLE
Mac optimization

### ISSUE THREAD

**Issue by KilluaZoldich** [lllyasviel/Fooocus#1150]
the app is incredibly versatile and easy to use, however waiting 1 hour to generate an image is not so optimal
I have a Mac M2 and the times are these:
Generating and saving time: 4254.15 seconds
Total time: 4268.19 seconds

**Comment by aponsin** [comment]
The M2 series has GPU cores and Neural Engine cores, isn't focus able to leverage them ?

**Comment by marek-guran** [comment]
> The M2 series has GPU cores and Neural Engine cores, isn't focus able to leverage them ?

Still uses RAM as VRAM just like Intel/Amd CPUs with integrated GPU. Nonetheless if you compare it with any GPU (the cpu integrated GPU), let's say with gtx 1650... It is very bad result for apple silicon since the Fooocus uses GPU and not CPU during render of images. So if laptop with M2 has 16 gigs of RAM, it will jump also into low ram mode and use disk that is configured for swap as additional "vram" and if it is single HDD, it will take 10 times more than if you used let's say M.2 nvme SSD with 3-4 GB/s write-read speeds since HDD would have to extract at least ~30 gb of compressed model, then constantly read and write and that needs to go to GPU to do its thing and apple GPU on that CPU can't do that like normal GPUs. (Since Fooocus uses primarily only GPU for generation)

**Comment by KilluaZoldich** [comment]
you know if there is a way to implement apple mlx to this?

**Comment by Alino** [comment]
I guess everywhere in the codebase where numpy and pytorch are used, it would have to pick up the MLX instead once Apple Silicone is detected. MLX has a Python API that closely follows NumPy

**Comment by Alino** [comment]
I am not a python dev and here is my very lazy and naive idea how it could work. There could be a wrapper class for NumPy and MLX which would call the correct lib based on architecture. The idea is to make it stupid simple and short so that it dynamically calls the method you want without redeclaring all NumPy methods.

```python
import platform
import numpy as original_np

try:
    import mlx.core as ml_np
    mlx_available = True
except ImportError:
    mlx_available = False


def is_apple_silicon():
    return platform.machine() == 'arm64' and platform.system() == 'Darwin'


class NumpyMLXWrapper:
    def __init__(self):
        self.use_mlx = is_apple_silicon() and mlx_available

    def __getattr__(self, name):
        def method(*args, **kwargs):
            if self.use_mlx:
                # Try MLX first
                try:
                    return getattr(ml_np, name)(*args, **kwargs)
                except AttributeError:
                    pass
            # Fallback to NumPy
            return getattr(original_np, name)(*args, **kwargs)
        return method


np = NumpyMLXWrapper()

```


then in the codebase we could just instead of doing this
```python
import numpy as np
```

do this
```python
import numpy_mlx_wrapper as np
```

and we don't have to probably touch anything else.

**Comment by KilluaZoldich** [comment]
> I am not a python dev and here is my very lazy and naive idea how it could work. There could be a wrapper class for NumPy and MLX which would call the correct lib based on architecture. The idea is to make it stupid simple and short so that it dynamically calls the method you want without redeclaring all NumPy methods.
> 
> ```python
> import platform
> import numpy as original_np
> 
> try:
>     import mlx.core as ml_np
>     mlx_available = True
> except ImportError:
>     mlx_available = False
> 
> 
> def is_apple_silicon():
>     return platform.machine() == 'arm64' and platform.system() == 'Darwin'
> 
> 
> class NumpyMLXWrapper:
>     def __init__(self):
>         self.use_mlx = is_apple_silicon() and mlx_available
> 
>     def __getattr__(self, name):
>         def method(*args, **kwargs):
>             if self.use_mlx:
>                 # Try MLX first
>                 try:
>                     return getattr(ml_np, name)(*args, **kwargs)
>                 except AttributeError:
>                     pass
>             # Fallback to NumPy
>             return getattr(original_np, name)(*args, **kwargs)
>         return method
> 
> 
> np = NumpyMLXWrapper()
> ```
> 
> then in the codebase we could just instead of doing this
> 
> ```python
> import numpy as np
> ```
> 
> do this
> 
> ```python
> import numpy_mlx_wrapper as np
> ```
> 
> and we don't have to probably touch anything else.

how do you implement this ?

**Comment by Alino** [comment]
the big chunk of code would be a separate file let's call it ```numpy_mlx_wrapper.py```
then you would replace those imports in the whole codebase to import from this class instead of numpy.

Then you would find out it does not work and have to face all the challenges. But it would require also a good testing and benchmarking to see if if it did not break anything and if it is effective.

**Comment by Alino** [comment]
I got an answer from one of the MLX members. It seems my idea is not that stupid.
https://github.com/ml-explore/mlx/issues/153#event-11237897293

**Comment by Alino** [comment]
I was playing around with this a bit but run into multiple issues and I don't have time to work on this. But if anyone would like to pick up from where I ended. Here is my code:

numpy_mlx_wrapper.py
```python
import platform
import numpy as original_np

try:
    import mlx.core as ml_np    
    mlx_available = True
except ImportError:
    mlx_available = False

def is_apple_silicon():
    return platform.machine() == 'arm64' and platform.system() == 'Darwin'


class NumpyMLXWrapper:
    def __init__(self):
        self.use_mlx = is_apple_silicon() and mlx_available
        self.skip_methods = ['cumprod'] # skip cumprod because it throws an error in MLX
        print(f"[MLX_WRAPPER] Initialized with use_mlx={self.use_mlx}")

    def __getattr__(self, name):
        print(f"[MLX_WRAPPER] Checking attribute '{name}' in MLX and original NumPy modules...")
        if self.use_mlx and name not in self.skip_methods:
            # Try MLX first
            try:
                attr = getattr(ml_np, name)
                print(f"[MLX_WRAPPER] Attribute '{name}' found in MLX module.")
            except AttributeError:
                # Fallback to NumPy
                print(f"[MLX_WRAPPER] Attribute '{name}' not found in MLX module. Falling back to original NumPy module.")
                attr = getattr(original_np, name)
        else:
            # Directly use NumPy
            attr = getattr(original_np, name)
            print(f"[MLX_WRAPPER] Attribute '{name}' found in original NumPy module.")

        # If the attribute is a method, return a callable
        if callable(attr):
            def method(*args, **kwargs):
                return attr(*args, **kwargs)
            return method
        else:
            # If it's not a method (e.g., dtype like np.uint8), return it directly
            return attr


np = NumpyMLXWrapper()
```

numpy_mlx_wrapper.test.py
```python
import unittest
from numpy_mlx_wrapper import np as np

class TestNumpyMLXWrapper(unittest.TestCase):
    def test_uint8(self):
        self.assertTrue(hasattr(np, 'uint8'))

if __name__ == '__main__':
    unittest.main()
```

good luck guys. I think this might not even improve the performance much and the MLX is not mature yet.
