### ISSUE TITLE
Uncompress file slow

### ISSUE THREAD

**Issue by spacephilosophy** [lllyasviel/Fooocus#1186]
It takes ages (it's been running a full day) to uncompress the file downloaded for windows.

**Comment by Krupakar-Reddy-S** [comment]
Since the windows standalone version comes with `python_embeded` along with all required dependencies preinstalled it tends to be large and takes a lot of time to uncompress, Instead of using default windows tool, try [7-Zip](https://www.7-zip.org/) it will help a bit but if it still takes a lot of time, a manual installation from the source code is recommended and can be followed from the [README.md](https://github.com/lllyasviel/Fooocus) file.

**Comment by khurramar** [comment]
If someone else is facing the issue. Turn off the antivirus and try again. It shouldn't take more than a couple of seconds.
