### ISSUE TITLE
"Guidance Scale" label is incorrect

### ISSUE THREAD

**Issue by Cretezy** [lllyasviel/Fooocus#1221]
**Describe the problem**
The label under "Guidance Scale" in the Advanced tab seems incorrect.

The current label is: Higher value means style is cleaner, vivider, and more artistic.

From my understanding, guidance scale works by "The higher the value, the more the image sticks to a given text input" ([source](https://getimg.ai/guides/interactive-guide-to-stable-diffusion-guidance-scale-parameter)). This means a lower value should be more "artistic".

The label should probably say something like: Higher value follows prompt more closely. Can be more creative at lower values.

**Comment by mashb1t** [comment]
In general you're right, but Fooocus uses an adaptive CFG scale, which differs from the values of normal CFG, see https://github.com/lllyasviel/Fooocus/blob/f31f3edeec7b7b64ab1bb893941cf9ab1a3522ac/modules/patch.py#L190.
Therefore, the label is indeed correct.

**Comment by alonsojr1980** [comment]
How does the FOOOCUS CFG relates to the normal CFG? A normal CFG of 7 translates into what in FOOOCUS?

**Comment by aelfwyne** [comment]
Since the entire world uses "CFG Scale" I am in agreement with the previous poster, there should be guidance as to how this relates to the FOOOCUS value. It is very difficult, if not impossible, to recreate shared prompts due to the changes in FOOOCUS terminology. Some guidance here and with other common settings that FOOOCUS has hidden or changed would be appreciated.
