### ISSUE TITLE
Canvas zoom for the inpainting canvas

### ISSUE THREAD

**Issue by anae-git** [lllyasviel/Fooocus#1247]
Can we get a canvas zoom feature similar to what https://github.com/richrobber2/canvas-zoom provides for A1111?
Fooocus has by far the best inpainting/outpainting backend. It would be nice if the frontend was spruced up a bit too.

**Comment by Tanoshimi** [comment]
I'm using Fooocus_win64_2-5-0 (not sure if that's a legit version or not) but I was wondering if there were a way to say how far we wanted to outpaint?  I was thinking I could give it new dimensions (like taking 512x512 to 1024x512), or even sliders for how much we want in each direction (like 2x left, 0.25x right, 0 up, and 1.5x down)?

**Comment by mashb1t** [comment]
@Tanoshimi Outpaint is not similar to the infinite canvas feature you might know from other tools but extends the image by 30% in selected directions.

**Comment by Tanoshimi** [comment]
> @Tanoshimi Outpaint is not similar to the infinite canvas feature you might know from other tools but extends the image by 30% in selected directions.

Sorry!  I meant Outpaint.  Is there a way to up that 30%?  

Basically, I need a character to appear on the right side of the image.  Fooocus is not really doing a great job of that, so I want to generate them in 512x512, but then Outpaint to the left until we're at 1025x512.  Something like that.  

I'd rather do it in 1 shot, rather than having to Outpaint more than once.

**Comment by mashb1t** [comment]
@Tanoshimi i'd propose th create an empty image / canvas, e.g. in paint, inserting which elements you want to have where (e.g. your already created image in the left), inserting this image in inpaint and draw a mask on the right for Fooocus to generate content for. Important is that you use mode "add objects" here to create new things.
Keep in mind that SDXL is based on 1024 aspect ratios, 512x512 us SD1.5 (not supported in Fooocus).

Your canvas should be a size selectable in the asoect ratios in Fooocus.

Hope this helps :)

**Comment by Tanoshimi** [comment]
@mashb1t It does, and it it doesn't. :D I tried what you suggested, made a 512x1024 image in Foocus (I know, resolution's wrong), then copied and pasted it onto the right side of a 1024x1024 image, then loaded that image into Fooocus, colored off the mask, set it to add objects, and told it the background I needed.  I got a good result.

But since I want to automate this, eventually trying to do it with the API, it's a bit of work, and I had to do stuff in an outside program (paint or photoshop).  

Would just be easier if I could tell outpaint to take my 512x1024 image and paint the left side of it out to 1024!  LOL.

Is that 30% in the webgui.py?  Hard coded into Outpaint? Somewhere in the settings?  No way to change it?

**Comment by mashb1t** [comment]
> Would just be easier if I could tell outpaint to take my 512x1024 image and paint the left side of it out to 1024! LOL.

You can certainly do so when doing changes to the code, but not with outpainting but impainting then.

> Is that 30% in the webgui.py? Hard coded into Outpaint? Somewhere in the settings? No way to change it?

You can change this, but it will not yield good results as foe outpainting the original image is used as context and elements will be extended. Using a resolution not native to SDXL will result in lower quality images.

You can adjust the code in https://github.com/lllyasviel/Fooocus/blob/main/modules/async_worker.py#L548-L564, replacing the 0.3 with whatever percentage you like, but as you'll then experience results will not be as good as extending the image programmatically (relatively easy using e.g. cv2) and then impainting (using a predefined mask), then do the inpaint.

For this case you might be better off using ComfyUI, if you do not have programming experience.
