### ISSUE TITLE
Connection errored out

### ISSUE THREAD

**Issue by xviovx** [lllyasviel/Fooocus#1297]
Hey there.

I am getting this error when I try to run Fooocus locally (on a humble GTX 1650).

Considering trying to run with Colab.

Please let me know if you have any suggestions. 

![Screenshot 2023-12-09 140026](https://github.com/lllyasviel/Fooocus/assets/71275388/28a8a583-3096-4107-97d2-629d438b37b4)

**Comment by mashb1t** [comment]
@xviovx lonks to https://github.com/lllyasviel/Fooocus/issues/1112

Your graphics card is on the brink of being able to run Fooocus but only with resizable BAR support and with enough system memory available.
Be prepared for a long (1min+) generation time though per image. Using Colab would IMHO offer a better user experience, but feel free to try locally.

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md

**Comment by aparker21** [comment]
I am getting the error as well.  I only have 3.88GB space on my SSD (where my operating system is running) but have 128GB free on my HDD.  Do I need more space on the SSD or should it still be working correctly since I have plenty of space (and can free more if needed) on my HDD?  If I have enough space overall, what are the thoughts on fixing the issue?  I have the Space Swap set to Automatic in Windows 10.

**Comment by zhincic** [comment]
Same error. Haven't found a single fix for this
