### ISSUE TITLE
cuda out of memmory

### ISSUE THREAD

**Issue by gouravraghuwanshi** [lllyasviel/Fooocus#1316]
when use this tool in RTX3050 this messege has shawn 

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacty of 4.00 GiB of which 2.92 GiB is free. Of the allocated memory 277.80 MiB is allocated by PyTorch, and 20.20 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Total time: 132.55 seconds

**Comment by Benliam12** [comment]
Would you mind sharing the chunk of code you are using to allocate this amount of memory?

**Comment by mashb1t** [comment]
please elaborate and check if Resizeable BAR is enabled.
Also see https://github.com/lllyasviel/Fooocus/issues/1240#issuecomment-1846720445

**Comment by AbhimanyuSingh2005** [comment]
I am also facing same issue. Can you explain what is Resizable Bar

**Comment by mashb1t** [comment]
@AbhimanyuSingh2005 you might also have a look at the now available troubleshooting guide here: https://github.com/lllyasviel/Fooocus/issues/1327

**Comment by miraculix95** [comment]
Hi, I am struggling with the same issue. I have 8GB VRAM. Ubuntu 22.04
My situation. 
- No swap space installed. -> I have now done it. I hope it will help.
- Checking for Resizeablebar (nvidia-smi q | grep -i bar -A 3) showed there is only 256MB, so it does not work, but activating it on Linux (using a GPU server), do not know how to do it - also difficult since not my own PC
- I still need to check if my Cuda is properly installed.

Can anyone help?

**Comment by AbhimanyuSingh2005** [comment]
This issues arises when model need more VRAM than available on GPU. I don;-'t know how to solve this, but if you want to use fooocus model, you can try it on google colab.
**Link of google colab->** [https://colab.research.google.com/github/lllyasviel/Fooocus/blob/main/fooocus_colab.ipynb](url)
