### ISSUE TITLE
improve the docs for Windows 11

### ISSUE THREAD

**Issue by robvaneck** [lllyasviel/Fooocus#1336]
I ran into some issues trying to install Fooocus on Windows 11, 
After extracting the compressed files and running `python launch.py`
I ran into the torch, ncvv bug

So here are my steps to install on Windows 11, which works

```
make sure you have
- python 3.10, not 3.12!
- pip
- virtualenv

git clone https://github.com/lllyasviel/Fooocus.git`
cd Fooocus
python -m venv fooocus_env
fooocus_env\Scripts\activate.bat
pip install -r requirements_versions.txt
python entry_with_update.py
```

feel free to copy paste into the docs

**Comment by mashb1t** [comment]
@robvaneck May i ask why you haven't decided to use the official way of installing Fooocus (the .7z file)?
https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#windows
It comes with its own embedded python 3.10 and venv. i assume you wouldn't have had to deal with the issues you mentioned.
Please provide some insights to optimise and streamline the installation process. Thanks!

**Comment by robvaneck** [comment]
@mashb1t I first tried the installer, but got an error.. I forgot what kind of error.
Plus, I think virtualenv is the way to go. It's how most python projects are installed, so I thought I might be good to add my install instructions for anyone looking

**Comment by mashb1t** [comment]
@robvaneck totally agree that venv is the way to go, which is why it is also included in the zip file.
I'd propose to close this issue and only use the zip as unexperienced users do not even have to use a terminal to install & run Fooocus and it's less steps + less prome to errors due to embedded python.
Thank you again for providing manual instructions on the setup, will reference this in the future for other users also following this approach.
