### ISSUE TITLE
C:\Windows\System32>.\python_embeded\python.exe -s Fooocus\entry_with_update.py The system cannot find the path specified.

### ISSUE THREAD

**Issue by Mjwilson82** [lllyasviel/Fooocus#1354]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
Running the run.bat file and i'm getting the above

**Full Console Log**
C:\Windows\System32>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
The system cannot find the path specified.

C:\Windows\System32>pause
Press any key to continue . . .

**Comment by ryeact-dev** [comment]
Does this issue already solve? I have the same issue

**Comment by ryyyn** [comment]
The issue here is that the batch file is not running from the directory where Fooocus is installed--that is why it can't find the files.
The simple workaround for running Fooocus would be to launch command prompt in the directory where it is installed, then paste the .bat contents. 

**That being said**, there was an underlying Windows permissions issue which caused me to get this issue: when I simply double-click the .bat file, I got a PermissionError when it attempted to create directories in my Program Files drive. When I right clicked and ran as administrator, CMD was initialized in the System32 directory just like yours is and I got the same error.

This was just one of a series of maddening permission issues, such as being unable to extract files to Program Files despite my account having Administrator role!
I searched online until I located the root cause: I recently upgraded to Windows 11 and the Owner of my C: drive was set to "Trusted Installer" instead of my own profile. If you (or anyone else who comes across this thread) experiences the same, here are the steps to address it. Make sure you are logged in with the profile you would like to have permissions, and that you are an Administrator. (Note I am not a windows expert and have no idea about the ramifications of doing this, but found that [thousands of other people have taken these steps over the past decade](https://answers.microsoft.com/en-us/windows/forum/all/permission-error-failed-to-enumerate-objects-in/93ea883f-853f-4981-a697-928bfbc71642)... so proceed at your own risk)
1. In Windows File Explorer, right-click on your C:/ driver (or whichever drive is giving you problems, or a specific folder therein) and select Properties. 
2. Select the Security tab and click Advanced.
3. If the name next to Owner is not your profile, click "Change" to update it. Enter your username in the text box. (If you don't know your username, open command prompt and type `echo %USERNAME%`). Click "Check Names" and hit Apply.
4. Check the box which says "Replace all child object permission entries with inheritable permission entries" and hit Apply.

Now if **this** gives you an error, as it did in my case, you may need to first take ownership of the drive/folders. To do so, execute in command prompt:
`takeown /f c:` (or a specific folder, if you don't want to ownership to apply to the entire drive)

Hope this might help someone!

**Comment by TeslaSoftware** [comment]
I had exactly the same error. 
I solved it by opening command prompt and navigating to the folder containing `Fooocus` and run the `run.bat` .

Essentially what was happening the instalation of `Fooocus` did not exist in the default path of command prompt which is `C:\Windows\System32`

**Comment by jacksands** [comment]
don't run as administrator

for some reason that was my problem

windows 11

**Comment by okiewardoyo** [comment]
> don't run as administrator
> 
> for some reason that was my problem
> 
> windows 11

Thanks so much, it works for me. Just double click run.bath , and don't execute as administrator

**Comment by TheNoob7** [comment]
@TeslaSoftware can you explain exactly how you did that?

**Comment by mahmud19777** [comment]
.\python_embeded\python.exe: can't open file 'C:\\Users\\ADMIN\\Downloads\\defooocus\\DeFooocus\\entry_with_update.py': [Errno 2] No such file or directory
Press any key to continue . . .
