### ISSUE TITLE
Regional prompter support

### ISSUE THREAD

**Issue by GuidoBartoli** [lllyasviel/Fooocus#1391]
**Is your feature request related to a problem? Please describe.**
To have more control over the placement of subjects within the generated image, it would be very useful to have native support for regional prompting.

**Describe the idea you'd like**
The idea comes from how the the [Regional Prompter extension](https://github.com/hako-mikan/sd-webui-regional-prompter) is employed in Stable Diffusion Webui. A basic implementation for Fooocus might be support for the [BREAK keyword](https://github.com/hako-mikan/sd-webui-regional-prompter#usage), while more extensive functionality might involve the assignment of [custom 2D zones](https://github.com/hako-mikan/sd-webui-regional-prompter#2d-region-assignment).

![2d](https://github.com/lllyasviel/Fooocus/assets/16103676/048a3db3-f034-4ddf-8e3e-6267057eff8b)

**Comment by lllyasviel** [comment]
this is discussed a while ago

the conclusion is that if inpaint is as good as Adobe Firefly Generative Fill, then all regional tricks are unnecessary.

so all future development will into improving the fundamental inpaint rather than similar distracting tricks.

And actually Fooocus already has the best and unique inpaint engine to enhance any SDXl model. You are posting this mainly because you havent tried more about Fooocus inpaint.

Fooocus inpaint is different from all other software. If you try Fooocus inpaint more, you will immediately begin to think that those regional tricks are not necessary.

**Comment by GuidoBartoli** [comment]
Thanks @lllyasviel, apparently I did not take full advantage of the potential of the inpainting function of Fooocus, perhaps I had underestimated it from the point of view of using it to place subjects or objects at precise points in the image. I thank you for the explanation, I will do some testing in this regard soon!
