### ISSUE TITLE
Loading the model takes extremely long

### ISSUE THREAD

**Issue by barni701** [lllyasviel/Fooocus#1401]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
Even after I downloaded the 531 Driver for my Nvidia RTX 4050 GPU it takes more than 3 minutes to generate 2 images.
I have more than enough VRAM and Memory

**Full Console Log**
![image](https://github.com/lllyasviel/Fooocus/assets/146190511/22ed4a12-e566-44c6-9876-872a9b6806a7)

**Comment by mashb1t** [comment]
You're using lowvram mode (either detected due to having too little VRAM available or you manually set the argument), which means it loads the model into SWAP or RAM, which is both less fast than loading the whole model into VRAM.
Are you using a HDD or an SSD as storage in your system? Especially in lowvram mode this could also have a huge impact.
If you set --lowvram yourself make sure to remove it (if possible with your GPU) to boost performance.

**Comment by barni701** [comment]
I am not sure why it detects that I have too little VRAM any ideas on how I can solve this?
Also I am using an SSD

**Comment by lllyasviel** [comment]
You may try to disable HDD swap and only enable SSD swap,
it should be possible in the step 7 in the screenshot of https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#system-swap
but this is a dangerous option and not very recommended

**Comment by resoftw** [comment]
I'm using only GTX 750ti with 2GB VRAM, and 32GB RAM on my PC, it doesn't take too long to load the checkpoint, except for the rendering time (steps).
but when I run it on my laptop with 16GB RAM and GTX 1060 6GB, it took very long time to load the checkpoint..
