### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by cwdragon** [lllyasviel/Fooocus#1423]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
After downloading the windows install and running the "run.bat" file I get the error log below.
I'm using 64 bit windows 11 with an AMD cpu and NVIDIA 3080, I've tried removing my regular python from the path
any ideas what could be going wrong here?

**Full Console Log**
C:\Users\cwdra\Downloads\Fooocus_win64_2-1-831>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.841
Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_version6Rundiffusion.safetensors" to C:\Users\cwdra\Downloads\Fooocus_win64_2-1-831\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors

Traceback (most recent call last):
  File "C:\Users\cwdra\Downloads\Fooocus_win64_2-1-831\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "C:\Users\cwdra\Downloads\Fooocus_win64_2-1-831\Fooocus\launch.py", line 107, in <module>
    download_models()
  File "C:\Users\cwdra\Downloads\Fooocus_win64_2-1-831\Fooocus\launch.py", line 75, in download_models
    load_file_from_url(url=url, model_dir=path_checkpoints, file_name=file_name)
  File "C:\Users\cwdra\Downloads\Fooocus_win64_2-1-831\Fooocus\modules\model_loader.py", line 24, in load_file_from_url
    from torch.hub import download_url_to_file
  File "C:\Users\cwdra\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 193] %1 is not a valid Win32 application. Error loading "C:\Users\cwdra\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\lib\curand64_10.dll" or one of its dependencies.

C:\Users\cwdra\Downloads\Fooocus_win64_2-1-831>pause
Press any key to continue . . .

**Comment by MichalZak17** [comment]
Hey [cwdragon](https://github.com/cwdragon),

It seems like the issue you're encountering is related to a compatibility problem with the `curand64_10.dll` file, which is a part of the PyTorch library. The error message `[WinError 193] %1 is not a valid Win32 application` suggests that there's a mismatch between the 32-bit and 64-bit versions of the software components involved. 

First, verify that the embedded Python version in your `Fooocus` application is 64-bit. You can do this by checking the properties of `python.exe` in the `python_embeded` directory. It should be compatible with your 64-bit system.

Also it's possible that the PyTorch installation within your `Fooocus` application is corrupted or incompatible. Try reinstalling PyTorch specifically for a 64-bit environment. You can do this by running the following command in your `python_embeded` environment:

   ```shell
   pip install torch -f https://download.pytorch.org/whl/torch_stable.html
   ```

Other explanation is error might be due to missing dependencies for the `curand64_10.dll` file. You can use a tool like Dependency Walker to check if all necessary DLLs are present and correctly loaded. If any dependencies are missing, you'll need to install them.

Since you're using an NVIDIA 3080, ensure your GPU drivers are up to date. Outdated drivers can sometimes cause compatibility issues with CUDA-enabled applications like those using PyTorch.

If these steps don't resolve the issue, it might be helpful to provide additional information such as any changes made to the system prior to this issue occurring or other relevant details. This will help in diagnosing the problem more accurately.

**Comment by lllyasviel** [comment]
hi first check if it is file corruption
then follow the CUDA Kernel Errors section here. https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#cuda-kernel-errors-might-be-asynchronously-reported-at-some-other-api-call

**Comment by cwdragon** [comment]
Hi @MichalZak17,
looks like it had something to do with the version of torch, I had to uninstall torch using pip and the reinstall
its worth noting this is a first time setup my only steps we're downloading the windows release and selecting run.bat

@lllyasviel I don't know if you want to add another section to the trouble shooting doc for this, to fix it I ran
python_embed/python.exe -m pip uninstall torch
python.exe -m pip install torch -f https://download.pytorch.org/whl/torch_stable.html

it did spit out some issues about being incompatible with torch vision, but I guess that's a separate issue I'll solve it it impacts me
