### ISSUE TITLE
PC keeps crashing 

### ISSUE THREAD

**Issue by karkanions** [lllyasviel/Fooocus#1426]
i have a windows 11  system with a ryzen 9 16gb ram a 1660ti 6gm gpu and when i run fooocus my ram maximizes and the computer crashes

**Comment by MichalZak17** [comment]
Hello [karkanions](https://github.com/karkanions),

I've noticed the issue you're facing with Fooocus causing crashes on your Windows 11 system, which has a Ryzen 9 CPU, 16GB of RAM, and a 1660ti 6GB GPU. While investigating the problem, I'd like to share some insights.

Firstly, I want to clarify that the VRAM might not be the root cause of the problem. I've personally tested Fooocus on a GTX 1060 3GB, and it performed well. Therefore, I recommend checking your graphics card drivers. There have been reports of newer Nvidia drivers (versions above 532) exhibiting slower performance. If your current driver is newer than 531, you might want to consider downgrading to Nvidia Driver 531 to see if it improves the performance.

Additionally, pay attention to your Virtual Swap and Disk Space settings. Ensure that Microsoft's Virtual Swap technique is enabled as it is essential for optimal performance. Also, make sure you have at least 40GB of free space on each drive to prevent "RuntimeError: CPUAllocator" issues.

Given that you are experiencing RAM maximization, it's essential to monitor your system's resource usage while running Fooocus. This will help identify specific processes or conditions that may be causing the spike in RAM usage.

If these suggestions do not resolve your issue, consider providing us with the complete specifications of your computer, including the RAM manufacturer, motherboard model, and the exact processor model. Additionally, including specific error messages, system logs, or any circumstances under which the crash occurs would be immensely helpful in understanding and addressing the problem more effectively. Your detailed information will enable us to provide you with a more accurate solution.

**Comment by MichalZak17** [comment]
Could you please attempt running `entry_with_update.py` with the `--always-gpu` flag? This flag will ensure that your computer utilizes the GPU for processing tasks, which might prevent crashes. 

Additionally, have you experienced any computer crashes under stress while playing other games or using applications like A1111? This information could help further diagnose the issue.

**Comment by lllyasviel** [comment]
hi please first take a look at https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md
and if you cannot find matched solution or if problem still, paste full log here

**Comment by karkanions** [comment]
Ive never experienced a crash in a game or anything beafore the problem is that foocus doesnt use the gpu and it only uses cpu and i cannot implement the flag even tho i opend the entry_with_update.py file

**Comment by lllyasviel** [comment]
hi please have a full console log, otherwise we are not able to look at problem.

**Comment by MichalZak17** [comment]
Just open the CMD in the same file as `entry_with_update.py` and use the command
```shell
$ python3 entry_with_update.py --always-gpu
```

or you can modify locally file `run.bat` just like below

```bat
.\python_embeded\python.exe -s Fooocus\entry_with_update.py --always-gpu
pause
```

**Comment by karkanions** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831> .\python_embeded\python.exe -s Fooocus\entry_with_update.py --always-gpu
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--always-gpu']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.841
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 6144 MB, total RAM 16309 MB
Set vram state to: HIGH_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce GTX 1660 Ti : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 253, in <module>
    refresh_everything(
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 233, in refresh_everything
    refresh_base_model(base_model_name)
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 69, in refresh_base_model
    model_base = core.load_model(filename)
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\core.py", line 151, in load_model
    unet, clip, vae, clip_vision = load_checkpoint_guess_config(ckpt_filename, embedding_directory=path_embeddings)
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\sd.py", line 469, in load_checkpoint_guess_config
    clip = CLIP(clip_target, embedding_directory=embedding_directory)
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\sd.py", line 101, in __init__
    self.cond_stage_model = clip(**(params))
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\sdxl_clip.py", line 41, in __init__
    self.clip_g = SDXLClipG(device=device, dtype=dtype)
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\sdxl_clip.py", line 12, in __init__
    super().__init__(device=device, freeze=freeze, layer=layer, layer_idx=layer_idx, textmodel_json_config=textmodel_json_config, dtype=dtype,
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\sd1_clip.py", line 81, in __init__
    self.transformer = model_class(config, dtype, device, ldm_patched.modules.ops.manual_cast)
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\clip_model.py", line 121, in __init__
    self.text_model = CLIPTextModel_(config_dict, dtype, device, operations)
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\clip_model.py", line 93, in __init__
    self.encoder = CLIPEncoder(num_layers, embed_dim, heads, intermediate_size, intermediate_activation, dtype, device, operations)
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\clip_model.py", line 57, in __init__
    self.layers = torch.nn.ModuleList([CLIPLayer(embed_dim, heads, intermediate_size, intermediate_activation, dtype, device, operations) for i in range(num_layers)])
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\clip_model.py", line 57, in <listcomp>
    self.layers = torch.nn.ModuleList([CLIPLayer(embed_dim, heads, intermediate_size, intermediate_activation, dtype, device, operations) for i in range(num_layers)])
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\clip_model.py", line 46, in __init__
    self.mlp = CLIPMLP(embed_dim, intermediate_size, intermediate_activation, dtype, device, operations)
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\clip_model.py", line 30, in __init__
    self.fc1 = operations.Linear(embed_dim, intermediate_size, bias=True, dtype=dtype, device=device)
  File "C:\Users\pmpag\OneDrive\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\nn\modules\linear.py", line 96, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB. GPU 0 has a total capacty of 6.00 GiB of which 0 bytes is free. Of the allocated memory 12.47 GiB is allocated by PyTorch, and 271.76 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Thats the output

**Comment by lllyasviel** [comment]
hi this is because 1660 does not support  --always-gpu
see also https://github.com/lllyasviel/Fooocus#minimal-requirement to see if your 1660 gpu speed is normal

**Comment by karkanions** [comment]
it runs at normal speeds and it doesnt crash but when i input a prompt in gradio  it says at the left bottom corner Waiting for task to start ... and it just does that

**Comment by mashb1t** [comment]
> it runs at normal speeds and it doesnt crash but when i input a prompt in gradio it says at the left bottom corner Waiting for task to start ... and it just does that

Just to make sure: Fooocus does NOT generate in normal speeds on your machine as it crashes  or is unresponsive  (with and without `--always-gpu`), correct?

**Comment by mashb1t** [comment]
closing as stale, feel free to reopen when providing new information

**Comment by alexamore** [comment]
Hello here same problem!
I've reinstalled Win10 and also tried on Linux Mint (where it comes out a "bus error" and linux stucks), both new installations and I have always problems with Fooocus.
I don't understand why the online version is (partially) able to do what I should be able to do without problems considering I have a Nvidia RTX2060 with 6GB and 32RAM (maybe here there is the problem with OS or Bios configuration).
Anyway, Windows always crashes when I give a task, what I've verified is that sometimes the system is able to finish the requested task just if I avoide to touch mouse and keyboard keeping closed all the windows down (this trick doesn't works always but on simple tasks).
Now I've tried to follow your suggestion creating a new .bat file with "--always-gpu" and actually the system doesn't crash anymore but it is so lazy (too lazy, probably 50 times slower) and the GPU works often around 5-10% (only when I keep opening the browser it seems to go higher).
The good thing is that I can keep working on other things but it's too lazy as "it doesn't go at work" :-D
My PC configuration is here: https://www.userbenchmark.com/UserRun/33645964 but with the difference of M.2 2GB each (2+2=4GB drives in total).
With "--always-gpu" CPU average is 8-10%, of 32GB RAM is used at 50% with python taking 13.000MB when very busy (otherwise is 5-6000MB).
I didn't test the system with videogames or other software but I've choosed this memory because it was supposed to be more powerful but maybe something wrong is configurated on the OS or Bios.

What can I do please? Is any workaround to use the RAM without letting crash everything? 
Thank you in advance,
Alex

Memory reference: DDR4 32GB 3600 G.SKILL F4-3600C16D-32GVKC (EAN 4713294223623)

![under stress](https://github.com/lllyasviel/Fooocus/assets/30070297/fef56b7d-f7f3-412b-a847-47b9d070f130)

**Comment by alexamore** [comment]
Hi @mashb1t , thank you for your reply. Well... do you really think it's a problem of my GPU? In the minimum requirement my card is not so bad and asks for 4GB considering I have 6GB and 32GB RAM instead of minumum of 8GB... I consider my system more than valid for using it. It's not normal I don't have to use my GPU, anyway I will try and I will come back to you. Thank you

**Comment by mashb1t** [comment]
Appendix: Above comment was writen under the assumption that you've already exhausted the options to update your driver to the latest version as well as set up swap correctly. Thank you for checking!

**Comment by alexamore** [comment]
well my friend... I'm starting thinking that Fooocus has broken my GPU. Before installing again Windows I found other problems with system, I posted another issue which was generated by Fooocus, now I don't have positive feelings about this.
I was able to generate some pictures till yesterday, now as soon as start generation using "run.bat" it crashes everything.

**Comment by mashb1t** [comment]
Maybe one last thing: can you please elaborate what you mean by "crashes everything"? Is your PC crashing or Fooocus, are there any logs in Fooocus console logs or the system event monitoring?

**Comment by alexamore** [comment]
ciao @mashb1t I would like to give you a feedback to both my posts, at end I've reached the "fooocus" of the problem :-D
it's my 980 PRO NVMe M.2 SSD 2TB. It has an issue and I've seen online many people have same problems when GPU is under stress. Even if mine is one of the last ones, it has the problem and I will open an RMA to Samsung. Hope it will help someone else too

**Comment by mashb1t** [comment]
Crazy, never thought about the NVMe being a problem. Thank you for sharing!

**Comment by ChrissNeo** [comment]
I also have the same issue, but swap is set on HDD to avoid the NVMe issue mentioned above and I still have the same issue. The freezing is happening only when trying to upscale or when using a refiner only.
When not using any refiner the base model loads very fast and with no freezes.

Also, if you get PYTORCH_CUDA_ALLOC_CONF, then use `--always-normal-vram` for 8 Gb VRAM, or `--always-low-vram` for 4 Gb.
