### ISSUE TITLE
App crashes when using two images with face swap as image prompt

### ISSUE THREAD

**Issue by gabcode1712** [lllyasviel/Fooocus#1450]
[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

App just crashes when I use two images with face swap selected as an image prompt, not a GPU error, what could be the cause for this?

**Comment by mashb1t** [comment]
just tested and it works for me.
Can you please provide the **full** output of your console log?

**Comment by gabcode1712** [comment]
no output at all, after loading the model, the app just stops working, also tried it in colab, automatically quits it.

**Comment by mashb1t** [comment]
Your RAM might be exhausted, which is why your process exits. Please make sure to enable Swap to make renderings possible even with RAM maxed (will be slower though). See https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md for more details.

Also see https://github.com/lllyasviel/Fooocus/issues/1558#issuecomment-1868166226

**Comment by mashb1t** [comment]
@gabcode1712 were you able to run Fooocus successfully on your machine whti increased/enabled swap?

**Comment by mashb1t** [comment]
closing as stale, feel free to reopen when providing new information
