### ISSUE TITLE
Settings save or bare minimum png meta data restore.

### ISSUE THREAD

**Issue by KINGLIFER** [lllyasviel/Fooocus#1456]
Fooocus seriously needs a bookmark or settings save. Like for real guys... at bare minimum a png meta data save. I wonder why this is left out.

All settings should have a way to save so when you reload Fooocus you do not have to re set every setting.

**Comment by lllyasviel** [comment]
*This is discussed a while ago, copy here:*

Currently the official way to track history is https://github.com/lllyasviel/Fooocus/discussions/160

We do have a plan to add some “project saving” button to save an opened project into a file like PhotoShop’s PSD.

However, the priority of this feature is not extremely high, because 

(1) the history log is functioning now, 

(2) midjourney does not have a save/load button and they also use log-based interface, since discord itself is a big log, 

(3) the goal of fooocus is stimulate “exploring new mediums of thought and expanding the imaginative powers of the human species”; if everyone begins with loading something, then they are less likely to think about more ideas and try more imaginative insights. (this point is controversial but do contribute to our decision making)

(4) Based on 3, may you ask when was the last time you actually wrote a prompt yourself describing an image in your own imagination? If that never happened, forget to load/paste something and write one sentence into Fooocus now!

Despite the above 1234, we still have plan to implement a “project saving” button.

Besides, Fooocus has a bottom line that it will never write any hidden data because many users of Fooocus do not know what is PNG/JPEG/meta/etc. They are from different fields beyond programmers, like magazine editor, journal writer, etc.

If Midjourney, Dalle, and Firefly begin to write hidden meta data into generated images, Fooocus will consider to also have this feature.

**Comment by partieboy** [comment]
"If Midjourney, Dalle, and Firefly begin to write hidden meta data into generated images, Fooocus will consider to also have this feature."

I dont think he is talking at all about any meta informations. Just for an option to save your settings.
Its hard for me also to re configurate everytime every part of the software (scale, sharpness, model, negative prompts and insert most of the usually needed positive prompt parts).
Ive read somewhere that you can edit your config but somehow it doesnt work for me :/

**Comment by lllyasviel** [comment]
> "If Midjourney, Dalle, and Firefly begin to write hidden meta data into generated images, Fooocus will consider to also have this feature."
> 
> I dont think he is talking at all about any meta informations. Just for an option to save your settings. Its hard for me also to re configurate everytime every part of the software (scale, sharpness, model, negative prompts and insert most of the usually needed positive prompt parts). Ive read somewhere that you can edit your config but somehow it doesnt work for me :/

edit "scale, sharpness, model, negative prompts and insert most of the usually needed positive prompt parts" here!

https://github.com/lllyasviel/Fooocus#customization

You can also look at

`Fooocus\config_modification_tutorial.txt` (this file will be generated after the first launch)

And for more fancy customization, you can have your own presets like:

https://github.com/lllyasviel/Fooocus/tree/main/presets

**Comment by KINGLIFER** [comment]
> "If Midjourney, Dalle, and Firefly begin to write hidden meta data into generated images, Fooocus will consider to also have this feature."
> 
> I dont think he is talking at all about any meta informations. Just for an option to save your settings. Its hard for me also to re configurate everytime every part of the software (scale, sharpness, model, negative prompts and insert most of the usually needed positive prompt parts). Ive read somewhere that you can edit your config but somehow it doesnt work for me :/

Exactly. This was a good breakdown on what Fooocus mandate is but it is a diversion of sorts.
I am talking about the lora, checkpoint, size settings and things of the like. each time you setup fooocus it has some type of setting. it isnt set to say... off or barebones like comfyui for example starts... So all that was said in this aspect is really non-sequitur. Can we have a way to remember settings please?

**Comment by VictorZakharov** [comment]
I think there should be an option to save both settings and metadata inside the image. At minimum, a separate tool/process to populate data from private logs into the images. Can be useful for publishing on civitai, for example, because currently it does not accept images generated in fooocus.

It does not matter whether Midjourney implements it or not. Those who are in the business of generating images can afford to buy a Midjourney sub, or any other sub (or several). Others who do it for fun, are using free services like fooocus.

**Comment by lllyasviel** [comment]
@VictorZakharov 
which file are you putting this line? `"default_loras": []`

it should work, do you mind pasting the file content to take a look?

**Comment by VictorZakharov** [comment]
@lllyasviel Fooocus/config.txt, I added default_loras prop at the end, rest was already there, never touched this file prior to this customization.

```
{
    "path_checkpoints": "G:\\Git\\StabilityMatrix\\Packages\\Fooocus\\models\\checkpoints",
    "path_loras": "G:\\Git\\StabilityMatrix\\Packages\\Fooocus\\models\\loras",
    "path_embeddings": "G:\\Git\\StabilityMatrix\\Packages\\Fooocus\\models\\embeddings",
    "path_vae_approx": "G:\\Git\\StabilityMatrix\\Packages\\Fooocus\\models\\vae_approx",
    "path_upscale_models": "G:\\Git\\StabilityMatrix\\Packages\\Fooocus\\models\\upscale_models",
    "path_inpaint": "G:\\Git\\StabilityMatrix\\Packages\\Fooocus\\models\\inpaint",
    "path_controlnet": "G:\\Git\\StabilityMatrix\\Packages\\Fooocus\\models\\controlnet",
    "path_clip_vision": "G:\\Git\\StabilityMatrix\\Packages\\Fooocus\\models\\clip_vision",
    "path_fooocus_expansion": "G:\\Git\\StabilityMatrix\\Packages\\Fooocus\\models\\prompt_expansion\\fooocus_expansion",
    "path_outputs": "G:\\Git\\StabilityMatrix\\Packages\\Fooocus\\outputs",
	"default_loras": [],
}
```

**Comment by lllyasviel** [comment]
@VictorZakharov
you have added a comma before the last line.
the last line do not need comma.

**Comment by VictorZakharov** [comment]
@lllyasviel It works, but I should not need to refer to the docs every time I need to change my config, right?

**Comment by KINGLIFER** [comment]
@VictorZakharov don't waste your time. These guys are on some other agenda... and Stability Matrix has some wierdos over there.  I discovered 3 bugs and tried to inform them and they attempted to do online bullying and of course they will deny but who cares. The point is clearly any piece of software should have a save. ANY. So the fact you have to debate that shows their logic. New year man... Do not waste energy.

**Comment by RexLeeGrey** [comment]
Midjourney is actually logged and records various weights, but hidden rather stealthily, each generated image has a corresponding jobid, you can use this string of jobid in discord with the /show command to call out the images you have ever generated, you can also use this string of jobid through the mj website to access and download all the in json file The metadata is saved in a json file, and I provided this route to the maker of the AutoJourney plugin, an mj plugin designed to automate the process of sending and downloading images and prompts on mj. He made the convenient downloader in the way I gave it, making it easy to read the prompt and a series of settings for each image, which is certainly convenient.
The current log way, on the other hand, is so laggy when I'm using it that it often stops my browser from responding for more than a minute and only loads out a few images at a time. I wouldn't be commenting in the questions section if I didn't have these problems.
![image](https://github.com/lllyasviel/Fooocus/assets/125941057/2118ccce-5774-4895-be3f-e42b971486c7)
![image](https://github.com/lllyasviel/Fooocus/assets/125941057/5b459b18-c032-40e3-835c-62b5628c8f8c)
![image](https://github.com/lllyasviel/Fooocus/assets/125941057/46d82b8a-2126-4834-b36b-d65b41dd8b7f)

**Comment by RexLeeGrey** [comment]
@lllyasviel Midjourney is actually logged and records various weights, but hidden rather stealthily, each generated image has a corresponding jobid, you can use this string of jobid in discord with the /show command to call out the images you have ever generated, you can also use this string of jobid through the mj website to access and download all the in json file The metadata is saved in a json file, and I provided this route to the maker of the AutoJourney plugin, an mj plugin designed to automate the process of sending and downloading images and prompts on mj. He made the convenient downloader in the way I gave it, making it easy to read the prompt and a series of settings for each image, which is certainly convenient.
The current log way, on the other hand, is so laggy when I'm using it that it often stops my browser from responding for more than a minute and only loads out a few images at a time. I wouldn't be commenting in the questions section if I didn't have these problems.
On the other hand, the project saving feature is not in conflict with "exploring new mediums of thought and expanding the imaginative powers of the human species", but perhaps it was generated at the time. Perhaps an image that doesn't feel right at the time can give birth to many ideas when I look back at it, and then I have to improve their formula to make the image the best it can be. As an art practitioner, images can't just be about creativity and ideas, I need to have the best form and texture in the image, and I'm constantly fine-tuning their formulas and optimizing them with other processes. Personally, I often let mj automatically mix images that interest me, and then subsequently select those that inspire me, I use it as a tool for dispersing my inspiration, and build folders to store, categorize, and classify them so that I can access them at any time, just as good scholars and writers put the ideas that they keep on sticky notes into categorized sticky note boxes.
![image](https://github.com/lllyasviel/Fooocus/assets/125941057/d74f6bf8-6ccd-4f14-bec2-3ce8e9978442)
![image](https://github.com/lllyasviel/Fooocus/assets/125941057/2118ccce-5774-4895-be3f-e42b971486c7)
![image](https://github.com/lllyasviel/Fooocus/assets/125941057/667a4bc6-3dd0-428d-81b0-1792eb216656)
![image](https://github.com/lllyasviel/Fooocus/assets/125941057/5b459b18-c032-40e3-835c-62b5628c8f8c)
![image](https://github.com/lllyasviel/Fooocus/assets/125941057/46d82b8a-2126-4834-b36b-d65b41dd8b7f)
![image](https://github.com/lllyasviel/Fooocus/assets/125941057/bf4c95e5-c6fb-4d48-a1b6-d4f01577c4d2)

**Comment by barepixels** [comment]
Here is an idea... Comfyui can save workflow.js   Maybe Fooocus can save a json file for each image.

Let say you generate 500 images while you sleep. (generate forever)
The next day you cherry-pick the top 10 that you love.  You immediately send them your NAS for backup and dump the 490 png and json files that you don't care for.  This way there is no metadata in the PNG but months from now you can resume the project by loading the image workflow json file.  Maybe there is an option to either use log.html or json

What do you guy think?

**Comment by mashb1t** [comment]
@KINGLIFER optional addition of metadata to images has just been released in https://github.com/lllyasviel/Fooocus/releases/tag/2.2.0
