### ISSUE TITLE
Instructions on how to do FACESWAP not in webpage.....?

### ISSUE THREAD

**Issue by LIQUIDMIND111** [lllyasviel/Fooocus#1683]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.
HOW DO I DO A FACE SWAP?

**Describe the problem**
NO ERRORS, I  JUST DON'T SEE ANY INSTRUCTIONS OR TUTORIAL IN YOUR PAGE.
**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.

**Comment by mashb1t** [comment]
This is not ChatGPT, please be more plolite next tiem and do not write in caps only.
See https://github.com/lllyasviel/Fooocus/discussions/830#discussioncomment-7547021 and below.

**Comment by LIQUIDMIND111** [comment]
> This is not ChatGPT, please be more plolite next time and do not write in caps only. See [#830 (reply in thread)](https://github.com/lllyasviel/Fooocus/discussions/830#discussioncomment-7547021) and below.

So, I never thought I need to graduate or take course on how to express myself in here. 

I was using the caps to contrast my request from the rest of the words. Still you never manage to reply.  That’s the least you could do. And chat gpt??? Wtf are you talking about??? You know what? I don’t care anymore for your help.  I can manage to find answers in other communities that don’t require a doctorate’s degree in conversations. Chill.

**Comment by LIQUIDMIND111** [comment]
> This is not ChatGPT, please be more plolite next time and do not write in caps only. See [#830 (reply in thread)](https://github.com/lllyasviel/Fooocus/discussions/830#discussioncomment-7547021) and below.

Whatever your point is THERE ARE NO INSTRUCTIONS ABOUT FACESWAP ON YOUR PAGE SO CHILL

**Comment by LIQUIDMIND111** [comment]
> This is not ChatGPT, please be more plolite next time and do not write in caps only. See [#830 (reply in thread)](https://github.com/lllyasviel/Fooocus/discussions/830#discussioncomment-7547021) and below.

Huh?? You ok?? Need help with something delicate??

**Comment by mashb1t** [comment]
>> So, I never thought I need to graduate or take course on how to express myself in here.
>> I was using the caps to contrast my request from the rest of the words. Still you never manage to reply. That’s the least you could do. And chat gpt??? Wtf are you talking about??? You know what? I don’t care anymore for your help. I can manage to find answers in other communities that don’t require a doctorate’s degree in conversations. Chill.
 
> Whatever your point is THERE ARE NO INSTRUCTIONS ABOUT FACESWAP ON YOUR PAGE SO CHILL

I was over exaggerating with "This is not ChatGPT", and mistook you writing in caps for shouting and being unsatisfied, which i'd like to apologise for.
Still, your answers (also) don't indicate a solution-oriented aproach and were objectively rude, which can and should be prevented in the future.

Context:
As you noticed, Fooocus does not provide information for any of the advanced methods.

This might be solved by providing an informative overlay, a help button or a link to an explanatory page in the future. For now we do not have advanced explanations on the page for any advanced options, as they are in general described in the advanced discussions https://github.com/lllyasviel/Fooocus/discussions/117 and https://github.com/lllyasviel/Fooocus/discussions/830. This is by design but may be changed in the future.
Hope this explanation helps.
