### ISSUE TITLE
Foocus folder gone > Cant run !python entry_with_update.py --share (Unable to run foocus colab gradio from my mount google drive )

### ISSUE THREAD

**Issue by Amit30swgoh** [lllyasviel/Fooocus#1730]
I dont want to instal jugger since i only use dreamshaperXL
also. i dont want to download anything since i already saved everything on my google drive 
but since fooocus folder is gone i cant run !python entry_with_update.py --share --always-high-vram
but im unable to create a gradio file .gradio 

![image](https://github.com/lllyasviel/Fooocus/assets/42430868/4f6b5793-1fe4-4070-b72e-5a742a54fe57)

![image](https://github.com/lllyasviel/Fooocus/assets/42430868/5af7df6c-f426-4768-9ddd-b8d3ed568818)

but since fooocus folder is gone i cant run !python entry_with_update.py --share --always-high-vram

do i need to change something ?
![image](https://github.com/lllyasviel/Fooocus/assets/42430868/39e02e02-6dde-4bd6-a068-1d099197c034)
![image](https://github.com/lllyasviel/Fooocus/assets/42430868/6efef182-6720-4fda-9904-28e185490945)

**Comment by poor7** [comment]
Now gradio.live gives error 504 Gateway timeout.

**Comment by Mladen2802** [comment]
Same issue here

**Comment by Amit30swgoh** [comment]
gradio working for me over all im just asking about useing my google drive so i wont need to download everything always

**Comment by eddyizm** [comment]
Looks like the Fooocus folder is there in your mounted drive. You probably need to remove the `git clone` code block because from your screenshot, looks like you are downloading the repo each time and then running it from scratch and not using your mounted folder. You can verify by checking what directory you are in when you run the command.

**Comment by Amit30swgoh** [comment]
> Looks like the Fooocus folder is there in your mounted drive. You probably need to remove the `git clone` code block because from your screenshot, looks like you are downloading the repo each time and then running it from scratch and not using your mounted folder. You can verify by checking what directory you are in when you run the command.

Ok so just femove the git clone?

**Comment by eddyizm** [comment]
Well, think about it, look at your screen, you see drive right? Is fooocus in there? My guess is yes. 
If so, just removing the git clone code block won't be enough.

You would do yourself a favor by trying to understand what is going on. You will need to change the calls so that python executes the code you already have downloaded. A lot of the sample instructions are set to pull down each time and you are deviating from that.

If you are familiar with linux, you should run the commands `pwd` and `ls` to identify your location, you will probably. need to change directories.

**Comment by Amit30swgoh** [comment]
> Well, think about it, look at your screen, you see drive right? Is fooocus in there? My guess is yes. If so, just removing the git clone code block won't be enough.
> 
> You would do yourself a favor by trying to understand what is going on. You will need to change the calls so that python executes the code you already have downloaded. A lot of the sample instructions are set to pull down each time and you are deviating from that.
> 
> If you are familiar with linux, you should run the commands `pwd` and `ls` to identify your location, you will probably. need to change directories.

Im super new in this with zero knolage in programminf for me its like reading chinies..
Could u pls ahow me and example so i will know better what to write.. ty so much

**Comment by mashb1t** [comment]
Make sure you're calling `entry_with_update.py` either while being located in `/content/Fooocus` or just use 
`!python /content/Fooocus/entry_with_update.py` instead

**Comment by eddyizm** [comment]
> Make sure you're calling `entry_with_update.py` either while being located in `/content/Fooocus` or just use `!python /content/Fooocus/entry_with_update.py` instead

From his screenshots, he is not using the standard file structure, eg the repo is not in that path but he mapped it to his drive, which puts in `/content/drive/MyDrive/Fooocus` 
At least that is what it looks like from the screenshot.

**Comment by mashb1t** [comment]
true, then https://github.com/lllyasviel/Fooocus/issues/423#issuecomment-1727767095 might just be the one-stop solution. Git command will fail, but it shouldn't matter as the commands just continue

**Comment by Amit30swgoh** [comment]
Thanks for the help both of you!
