### ISSUE TITLE
Batch processing folder for Image Prompts

### ISSUE THREAD

**Issue by RodTDai** [lllyasviel/Fooocus#1790]
Hey guys!

If we have an way to add a folder with images as a changing reference for image prompt (with all modes), should be really nice.
Thanks

**Comment by mashb1t** [comment]
This proposal drastically reduces the possibilities compared to the Gradio UI IP functionality as you can only select one type of IP instead of multiple.
Fooocus currently only supports a maximum of four images in IP, but this can individually be extended if needed.
I assume you can already do this by using one of the APIs (built-in Gradio or REST via https://github.com/konieshadow/Fooocus-API), feel free to check this out!

**Comment by RodTDai** [comment]
We really need some sort of image batch processing, it is important.
For example, i hage a lot of references for pose elements in my creation, i want just to use all my references and recreate in diferent styles. It also very good for doing recursion with generated images, over and over.

**Comment by mashb1t** [comment]
This might be a better use case then for A1111, as the batch features are already jntegrated there pretty well. Another user is already working on a batch upscaling, but there currently are no plans (yet) for batch image prompt references.

**Comment by finkbom** [comment]
im curious i could batch with automatic1111 or forge but fooocus has a way of mixing images and control net that seems so much better than the combinations i come up with in those ....so i favour adding batch to fooocus even though i should be able to do the same in those technically ...there feels like a bit of special source going on in foocus image prompting ....prehaps im just imagining it or am being lazy  but would love to have a way to que up a batch of images especial for controlnets
