### ISSUE TITLE
Where is the visualization.py file? It is missing in Fooocus/fooocus_extra/facexlib

### ISSUE THREAD

**Issue by rvdd1962** [lllyasviel/Fooocus#1799]
Will it crash the program?

line 216 in face_utils.py ---> from fooocus_extras.facexlib.visualization import visualize_detection
line 235 in face_utils.py ---> visualize_detection(img_ori, [bboxes], f'tmp/{img_name}_det.png')

**Comment by mashb1t** [comment]
The class face_utils.py is never called as main afaik, which is why the import will never be called.
Also the path https://github.com/lllyasviel/Fooocus/blob/f298ebca76054ccaeb3030e5ff0544956ed5ad9f/extras/facexlib/utils/face_utils.py#L218 does not exist on every device.
@lllyasviel is this code intended to be there, maybe for testing purposes, or can it be cleaned up?

**Comment by rvdd1962** [comment]
Thx for the quick response dev-team. Much appreciated. I've commented out that specific import call in the source file. If i see any more of this or other strange behavior in the code .. i'll report them to your team.
