### ISSUE TITLE
ip adapter v2

### ISSUE THREAD

**Issue by nivibilla** [lllyasviel/Fooocus#1842]
although its only for sd1.5, for people who are using refiners that are sd1.5 checkpoints it would be good. (in my testing realistic vision sd version + juggernaut is really good)

Also i noticed that the refiner doesnt make use of the face embeddings I think, because as soon as it swaps the face is changed completely.

Sample code for V2
https://colab.research.google.com/drive/1rD69EGCsBh22sHBsvBX-k2NOPTSjLQoi?usp=sharing

**Comment by mashb1t** [comment]
Thank you for providing the link to the playbook.
The issue https://github.com/lllyasviel/Fooocus/issues/1522 more or less also covers the SDXL version of this IP adapter, which is why i'd propose to close this issue as duplicate.
Feel free to reopen if you don't think this is related and/or should be implemented separately.

**Comment by nivibilla** [comment]
Np thanks.
