### ISSUE TITLE
大神 哪天有空可以这段代码帮忙改下

### ISSUE THREAD

**Issue by rookiehan** [lllyasviel/Fooocus#1874]
![1704972612386](https://github.com/lllyasviel/Fooocus/assets/19852119/cd388439-a827-407c-94f6-3bf168972ff4)
VAE的文件名下载后后缀是pt，程序每次检查时pth，每次启动都会过不去，暂时只能删了这段，大神啥时候有空可以改一下哈。

**Comment by xhoxye** [comment]
为什么要修改代码？如果是自动下载，程序会自动修改后缀，如果是自己另外下载，你可以下载后自行修改vae的后缀，难道是因为你要使用同一个vae用于另外的程序？
Why change the code? If you download it automatically, the suffix will be modified automatically. If you download it separately, you can modify the suffix of vae after downloading it. Is it because you want to use the same vae for another program?

**Comment by rookiehan** [comment]
> 为什么要修改代码？如果是自动下载，程序会自动修改后缀，如果是自己另外下载，你可以下载后自行修改vae的后缀，难道是因为你要使用同一个vae用于另外的程序？ Why change the code? If you download it automatically, the suffix will be modified automatically. If you download it separately, you can modify the suffix of vae after downloading it. Is it because you want to use the same vae for another program?

因为下载的文件名是根据下载链接给的，但是下载链接的文件后缀少了个h，但是程序还是会找pth这个后缀的文件，就会导致到每次都找不到，一只要下载。

**Comment by RodTDai** [comment]
嘿伙计们，这只是一个建议，但为什么不在开发帖子中统一用英语书写呢？这肯定会帮助大家。谢谢

**Comment by mashb1t** [comment]
@rookiehan currently doing issue cleanup. Is this issue still relevant or can it be closed?
