### ISSUE TITLE
Upscaling images should only generate one image

### ISSUE THREAD

**Issue by f0n51** [lllyasviel/Fooocus#1956]
**Is your feature request related to a problem? Please describe.**
After generating 4 images out of one prompt, I'd like to upsale one of these images. I drag and drop them to Image Prompt > Upscale or Variation and choose Upscale (2x). Fooocus then upscales this one image 4 times (the amount thats selected in the 'Image Number' slider / textbox). All four upscaled images are exactly the same. 

![image](https://github.com/lllyasviel/Fooocus/assets/155714366/083b7e20-8513-42ec-8d4f-9caa016fbd12)

**Describe the idea you'd like**
To save time and hardware costs, we could disable the 'Image Number' slider / textbox or set a default of 1 when Image Prompt > Upscale is selected.
Additionally, the aspect ratios are irrelevant when upscaling an image.

**Comment by mashb1t** [comment]
This is intended as the 1.5x and 2x Fooocus upscaling methods use AI upscaling, which in fact differs slightly for each upscaling generation.
Upscale 2x (Fast) behaves exactly the way as you described in your expectations, it does not care about the input of image amount and returns one image no matter what. This is due to only doing normal upscaling without re-rendering with SDXL.

Closing as won't fix, hope this is understandible for you.
