### ISSUE TITLE
Question/bug regarding photo editing.

### ISSUE THREAD

**Issue by adindozo** [lllyasviel/Fooocus#2030]
First time writing anything on github, web dev here. Correct me if I am writing at wrong place.

Is it possible to send picture of X to this model and it generate a little different X? Like can it be used for image editing, for example I send it picture of parking lot with 5 cars and I want to remove 1 car from image, can this model do it? Can this model change color of sky in photo? Can it change eye color? Just small editing based on my prompt. As I see in picture it did not work well.
![image](https://github.com/lllyasviel/Fooocus/assets/100275345/767c29a9-f73e-4d98-a5d0-d03812d33d43)

**Comment by mashb1t** [comment]
Hey @adindozo, this is more or less the right place, better for questions would be the [Q&A section](https://github.com/lllyasviel/Fooocus/discussions/categories/q-a) in our discussions instead of an issue.
SDXL does not understand natural language prompts very well, you have to describe what you want to have in the picture, not what you want to change.
Writing "parking lot with 4 cars" might work as prompt, but you might be better off using inpainting.
Feel free to try it in Image Prompt > Inpaint.
Looking forward to hear about your results.

**Comment by xhoxye** [comment]
Inpaint can delete objects
