### ISSUE TITLE
PLEASE ASK for download models while installation

### ISSUE THREAD

**Issue by kalle07** [lllyasviel/Fooocus#2176]
Is your feature request related to a problem? Please describe.
yes, all in germany has slow internet, that means ~2-10MB/s
so i need 15min to download a 7GB model

Describe the idea you'd like
ask while installation "downlaod model (y/n)"
because maybe i have all models already but not in the directorey fooocus espexct : D

**Comment by mashb1t** [comment]
This is not possible for installation as you need one model in order to run Fooocus at all. If you already have the juggernaut v8 model you can simply c&p it zo the models folder with the name expected in Fooocus to prevent a download.
As soon as you have one model, you may decide to never download any other model ever again (already the default for model updates, if you don't explicitly set the flag for this you'll only be informed that a new model is available).
When you switch presets Fooocus will also download the model required to run the preset.

Closing as invalid.
