### ISSUE TITLE
[win10] Falling asleep after finishing work on the application results in a crash with DRIVER_POWER_STATE_FAILURE error in the dump

### ISSUE THREAD

**Issue by exel5** [lllyasviel/Fooocus#2202]
windows 10 (regularly updated)
- NVIDIA GeForce RTX 3060 12GB graphics card
- Latest drivers installed from the NVIDIA website
- Latest version of fooocus installed from here
- After working with the application, I terminate run.bat using ctrl+c
- Put the computer into sleep mode
- After a minute of waiting, **the computer shuts down instead of going to sleep**.
- in the system event log I see information about an error during sleep transition, a dump is created in C:\Windows\MEMORY.DMP
- I read the dump using windbg, it says:

DRIVER_POWER_STATE_FAILURE (9f)
A driver has failed to complete a power IRP within a specific time.
Arguments:
Arg1: 0000000000000003, A device object has been blocking an IRP for too long a time
Arg2: ffffa00cd0fad120, Physical Device Object of the stack
Arg3: ffff84855ee3f750, nt!TRIAGE_9F_POWER on Win7 and higher, otherwise the Functional Device Object of the stack
Arg4: ffffa00ce8cc6ae0, The blocked IRP
Debugging Details:
Implicit thread is now ffffa00c`dc5d4040
Unable to load image \SystemRoot\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_2fe7c165c5dd3267\nvlddmkm.sys, Win32 error 0n2

- I check the file \SystemRoot\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_2fe7c165c5dd3267\nvlddmkm.sys, it is present and reads normally.
- Without running fooocus, the computer goes into sleep every day without any problems, but every time I tried to put it to sleep after running the application and exiting through ctrl+c, I observed such an error.

**Comment by MichalZak17** [comment]
Did you change your GPU recently without reinstalling the windows? Sometimes it might be the case, because of the old drivers that are theoretically uninstalled, but still affecting the new GPU with its drivers, causing the GPU to not properly dump Fooocus memory after exiting. In this case, it should be reproducible with some other graphic programs or games. Could you attach any other information from **Windows Event Viewer**  `Windows Logs > System`? It would help us to diagnose the source of this problem.

**Comment by mashb1t** [comment]
@exel5 thank you for reporting. Please check the windows events log as described above.
Is there any terminal output of Fooocus when stopping it and did you close the terminal? Did you stop a rendering before cancelling with ctrl+c or similar or was Fooocus idling?

**Comment by exel5** [comment]
- right, I installed a new graphics card (without reinstalling windows), on which it became possible to run fooocus, after that I encountered such a problem. I hardly play resource-demanding games, but after playing Civ5, going to sleep and waking up went smoothly.

- I pressed ctrl+c when fooocus was in an idle state, it didn't seem to produce any output after pressing ctrl+c, there was only a message confirming termination, offering to press Y/N, I pressed Y and the console closed. But I will check the output more carefully.

- I look at one of the recent crashes:
in the log, there are three error records at the time when I turned on the computer after the crash, the crash occurred at 5:40:48, at that time there were no records with errors or warnings:

> 28.01.2024 11:53:56 (critical): The system rebooted, completing work with errors. Possible reasons for the error: the system stopped responding to requests, a critical failure occurred, or the power was unexpectedly disconnected.
> 28.01.2024 11:54:02 (error): The previous system shutdown at 5:40:48 on ‎28.‎01.‎2024 was unexpected.
> 28.01.2024 11:54:13 (error): The computer was rebooted after a critical error. Error code: 0x0000009f (0x0000000000000003, 0xffffac8d6e19e060, 0xffffbc885b43f750, 0xffffac8d7879e010). Memory dump saved to: C:\WINDOWS\MEMORY.DMP. Report code: 3d634c89-0f49-41a8-9c83-e77c380659da.

**Comment by MichalZak17** [comment]
In this case, most likely it's a problem with old drivers, as I said before. A clean reinstallation of windows should fix the issue. 

> 28.01.2024 11:54:13 (error): The computer was rebooted after a critical error. Error code: 0x0000009f (0x0000000000000003, 0xffffac8d6e19e060, 0xffffbc885b43f750, 0xffffac8d7879e010). Memory dump saved to: C:\WINDOWS\MEMORY.DMP. Report code: 3d634c89-0f49-41a8-9c83-e77c380659da.

This error is associated with `DRIVER_POWER_STATE_FAILURE` which occurs due to incompatible or outdated drivers and can be seen sometimes when you're trying to put your computer into sleep mode. 

Related article: https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x9f--driver-power-state-failure

If you want to investigate it even further, you can share under this issue memory dump from file `C:\WINDOWS\MEMORY.DMP` and report code `3d634c89-0f49-41a8-9c83-e77c380659da`. Thanks to that information, we might be able to diagnose the precise cause of the failure. Analyzing the memory dump file can provide insights into what the system was doing at the time of the crash, including which drivers were loaded and potentially which one caused the failure.

If you're willing to reinstall your Windows, let us know if it fixed the issue as expected.

**Comment by mashb1t** [comment]
Closing as stale, feel free to reopen/provide further feedback.
