### ISSUE TITLE
Progress bar stuck

### ISSUE THREAD

**Issue by Jaysonbaby** [lllyasviel/Fooocus#238]
<img width="1280" alt="Desktop Screenshot 2023 08 22 - 17 19 13 51" src="https://github.com/lllyasviel/Fooocus/assets/142886905/d551c271-ff6d-4d80-a1c1-7e964998a549">

**Comment by MattRM2** [comment]
I have the same problem and my HDD activity is high. This HDD activity is high including when I do nothing (yes, I already have the model).

Is it possible that the models for SDXL took 30 min to load in Fooocus ? Because I think it's this. Only 3-4 minutes under ComfyUI.

Maybe is better that the homepage not open before Fooocus was really up to run, or maybe a progress bar during the model loading.

Thx

**Comment by Jaysonbaby** [comment]
I solved this problem, you just need to download the model via the link given by the author, and not automatically by command.
<img width="1280" alt="Desktop Screenshot 2023 08 23 - 12 15 35 53" src="https://github.com/lllyasviel/Fooocus/assets/142886905/374a13b2-9420-4f8b-ba75-fc761817a3b7">

**Comment by MattRM2** [comment]
> I solved this problem, you just need to download the model via the link given by the author, and not automatically by command. <img alt="Desktop Screenshot 2023 08 23 - 12 15 35 53" width="1280" src="https://user-images.githubusercontent.com/142886905/262551989-374a13b2-9420-4f8b-ba75-fc761817a3b7.png">

Hi,

But I already have the models in the good folder that I copied from my ComfyUI installation. The startup is long I think because of the loading of the base and refiner model if I well understand the messages in the terminal ;) Why it's more long than ComfyUI, don't know. In my case, it's not very an issue, it's more a performance complain on startup performance.

After this loading, it's ok, it works fast, just a long delai during startup and as this loading part is still running but the server page is already open, I have thought it was a bug.

Matt
