### ISSUE TITLE
[Feature Request]: Support multiple seeds for image generation

### ISSUE THREAD

**Issue by RubberGoose246** [lllyasviel/Fooocus#2471]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Regenerate specific images by using seeds of previously generated images. I know that logs are created into outputs subdirectory. But I appreciate if I can regenerate the same seed images by applying changed other settings Styles, Resolution and so on.

### Proposed workflow

Proposal 1: Support multiple seeds by separating with comma like CSV to the current seed textbox.
Proposal 2: Expand the current seed textbox to a textarea with scroll bars (both vertical and horizontal are preferable) and then same as above regarding CSV.

**Comment by QuantumCrazy** [comment]
I was thinking about something similar, for people who want to setup their systems to run through long generations and be a bit automated. Something like entering multiple prompts separated by a comma. The system then generates each prompt and outputs images then moves automatically to the next prompt and so on. Each prompt will have the same settings applied to make things easier as per config file. In terms of seed, same concept but user clicks a checkbox "seed" instead of "prompt", separated by comma.

**Comment by mashb1t** [comment]
For prompts you can use the new array syntax and freeze seed checkbox, e.g. `[[red,blue]] flower` and image number 2.
Multiple seed inputs won't be supported as this clutters the UI and is only a very niche feature which might be also provided in a fork. You already have multiple ways of regenerating images, e.g. private log or image metadata.
