### ISSUE TITLE
RAM and CPU usage - Making attention of type 'vanilla-xformers'

### ISSUE THREAD

**Issue by carpealexdiem** [lllyasviel/Fooocus#265]
GPU: GTX 1660 Super 6gb VRAM
RAM: 32gb
SSD: M.2 2TB with 1.4TB free

Every time I start it the RAM goes to 70%+ and once I press on generate it skyrockets to 100%, the CPU to 80% and the GPU around 3 to 5%.

The only thing related that I can see in the output is this: making attention of type 'vanilla-xformers' 

Already tried changing the page file, pointing it to the drive where fooocus is installed and also increasing but the problem is the same.

How to solve this? Thanks!

**Comment by wenlibin02** [comment]
Did the code throw exception? If not, maybe you should just give it some time.

In my case, the maximum host memory use of the program infinitely approaches the limit, with a few MB left…  yet it never crashes. After a while, the program is ready, and there will be  a few GB free memory. Once I click ‘generate’, the GPU load is low but not zero, maybe due to low efficiency of memory operations. It produces images within minutes.
