### ISSUE TITLE
[Feature Request]: All styles generated with same prompt with one check-box

### ISSUE THREAD

**Issue by simartem** [lllyasviel/Fooocus#2880]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

All styles are generated with one click for the given prompt

### Proposed workflow

1. Go to "Styles" Tab
2. Press the related check box (Generate ALL styles)
3. This action uncheck and disables ALL other style options

### Additional information

![req1](https://github.com/lllyasviel/Fooocus/assets/148996864/83ae9ba7-c266-4a31-aead-11f187e014ca)

* With today's powerful GPU's, one can generate an image for a single style within a few seconds (especially using turbo and lightning models).

* It is a need to know which styles give better results for given prompt.

**Comment by mashb1t** [comment]
Adding this feature has to be carefully considered as users either need to be educated first or hosting providers need a flag to disable this feature especially as this can block ressources for an extended amount of time, which may not be intended.
Gradio also will become a bottleneck as the preview gallery will freeze at such a big amount of images as well as RAM and general resource needs will skyrocket due to the need to encode all image prompts to conditions before the actual rendering.

Adding the checkbox/button/similar and corresponding code is not the issue, but this is certainly a challenge for the hardware.

Are / were you aware of the impact?

**Comment by mashb1t** [comment]
@simartem bump, happy to hear your feedback
