### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by Klaster1** [lllyasviel/Fooocus#3]
After starting, Fooocus exists with a "RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx" error.
```
C:\Users\Klaster_1\Downloads\Fooocus_win64_1-1-10>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 1.0.15
Inference Engine exists.
Inference Engine checkout finished.
Traceback (most recent call last):
  File "C:\Users\Klaster_1\Downloads\Fooocus_win64_1-1-10\Fooocus\entry_with_update.py", line 45, in <module>
    from launch import *
  File "C:\Users\Klaster_1\Downloads\Fooocus_win64_1-1-10\Fooocus\launch.py", line 81, in <module>
    from webui import *
  File "C:\Users\Klaster_1\Downloads\Fooocus_win64_1-1-10\Fooocus\webui.py", line 6, in <module>
    from modules.default_pipeline import process
  File "C:\Users\Klaster_1\Downloads\Fooocus_win64_1-1-10\Fooocus\modules\default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "C:\Users\Klaster_1\Downloads\Fooocus_win64_1-1-10\Fooocus\modules\core.py", line 8, in <module>
    import comfy.model_management
  File "C:\Users\Klaster_1\Downloads\Fooocus_win64_1-1-10\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\model_management.py", line 104, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\Klaster_1\Downloads\Fooocus_win64_1-1-10\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\model_management.py", line 74, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\Klaster_1\Downloads\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 674, in current_device
    _lazy_init()
  File "C:\Users\Klaster_1\Downloads\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

C:\Users\Klaster_1\Downloads\Fooocus_win64_1-1-10>pause
Press any key to continue . . .
```
Running on Windows 11 and AMD Radeon RX 7900 XTX.

**Comment by icecore2** [comment]
Same issue with RX 6700 XT.

**Comment by johan-lejdung** [comment]
Same on AMD 6750XT

**Comment by Small-Ku** [comment]
Related: https://github.com/comfyanonymous/ComfyUI/issues/160

**Comment by ahgera** [comment]
[ComfyUI already has support](https://github.com/comfyanonymous/ComfyUI/blob/master/comfy/model_management.py#L31) for AMD cards on Windows via Microsoft's DirectML, but it has to be activated through a CLI argument (--directml). Since Fooocus imports Comfy directly I don't see any way of setting the `args.directml` value to anything from Fooocus' code.

I tried to hack around this in the Comfy repository. First by changing `if args.directml is not None:` to `if not torch.cuda.is_available() and platform.system() == "Windows":`, but Fooocus for some reason pulls down the latest Comfy version from git at every start, thereby overwriting any changes.

So I commented out [that code](https://github.com/lllyasviel/Fooocus/blob/main/launch.py#L29), and after a while I got the web UI running, but i was unable to generate any images since I apparently have too little RAM in my old computer (12 GB):
`RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 84934656 bytes.`

The GPU and VRAM was barely used during this, so there was some bug still preventing DirectML to be used I think.

On top of that xFormers complains that it was built for PyTorch with Cuda, and I could find any way of either installing a CPU only version, or disable it.

---

I got slightly better results trying to use the same SDXL models in ComfyUI, but ultimately I got out of memory error there as well and gave up.
`[W D:\a\_work\1\s\pytorch-directml-plugin\torch_directml\csrc\engine\dml_heap_allocator.cc:120] DML allocator out of memory!`
At least this time i could see that both the GPU and VRAM was being used, but I'm guessing the limiting factor is still RAM since I got 8 GB VRAM and there were still some free.

**Comment by chenshiwei-io** [comment]
some on  Amd RX588

**Comment by xiao-xiaozi** [comment]
same on Amd 580

**Comment by Roninos** [comment]
RX 5700XT not work

**Comment by SkyHype2000** [comment]
AMD Radeon RX 6750 XT does not work here either

**Comment by lllyasviel** [comment]
See also https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#minimal-requirement

**Comment by kenwong1** [comment]
I've been using Fooocus on a 7900 XTX and it seems to work. Just need to make the changes mentioned in https://github.com/lllyasviel/Fooocus/issues/624#issuecomment-1757327660

I would like to see some optimizations done to make it faster on AMD cards though

**Comment by SkyHype2000** [comment]
thanks it works now ^^

**Comment by kenwong1** [comment]
The minimum requirements that @lllyasviel posted above says 16GB GPU memory required for AMD on Windows
