### ISSUE TITLE
[Feature Request]: Output subfolders

### ISSUE THREAD

**Issue by ErroneousBosch** [lllyasviel/Fooocus#3041]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Allow the user to add in a subfolder/tag for output of the current request (i.e. "My_cool_project" or "Character-1"). This would allow the outputs for particular projects to be grouped together, help with organizing output generated on the same day but for different projects, and give smaller logs. Have it create a new folder if the requested one doesn't exist.

For accessing, either the "History Log" link could be come a dropdown with an "Open Log" button.

### Proposed workflow

1. Go to Settings > Output Folder (or "Tag", or "Project", etc.),  down by Output Format.
2. Type in a folder name (w/ auto-hinting/autocomplete) - No spaces(?)
3. Folder is created when output is generated, and prepended to the date folder target

**Comment by mashb1t** [comment]
On the scope of this repository this is not applicable as there are also image generation services out there using Fooocus and the folder structure of outputs shouldn't differ (at least not the location of the log.html).
What we could do is to add subfolders for images only, but log.html has to stay one file. Also folder context path injections like `../` have to be prevented.
Would you like to contribute the implementation?

**Comment by V1sionVerse** [comment]
You can redirect the `Fooocus/outputs` directory at runtime, either by e.g. making an NTFS junction to a different target directory (e.g. for a specific project).

Here's how you would do that on Windows:
- Rename the `outputs` directory to e.g. `outputs.bak`
- Put the code below into a `.bat` file and edit the assignment of `LINK_PATH` in accordance with your Fooocus installation
- Drag and drop your target directory onto the `.bat` file to automatically mount it as the Fooocus output directory
```batch
@echo off

set LINK_PATH=D:\Fooocus\outputs

if "%~1"=="" (
    echo Error: No target directory provided.
    exit /b 1
)

set TARGET_DIRECTORY=%~1

echo Attempting to remove existing link or (empty) directory at `%LINK_PATH%`...
rd "%LINK_PATH%"

echo Creating new junction from `%LINK_PATH%` to `%TARGET_DIRECTORY%`...
mklink /J "%LINK_PATH%" "%TARGET_DIRECTORY%"
```

Note: This should still be safe to use if you didn't rename the `outputs` folder because `rd` only removes directories that are either completely empty or file system links. In that case, the script won't have any effect and will simply fail to create a link.
