### ISSUE TITLE
getting stucked at "Processing text encoding ..." stage

### ISSUE THREAD

**Issue by ahmadpromax** [lllyasviel/Fooocus#319]
hey guys 
hope you are doing fine!
### it just gets stucked and the results takes like forever

Graphic:
**nvidia 4GB 1050ti**
CPU:
**core i7 7700HQ**
Ram:
**16 GB**
----------------------------
i've wanted to experience much more faster image generation without any limit 
but it seems i'm just experiencing issues!

**Comment by charlotte686** [comment]
me too.
I completely followed the instructions to download and set it up, but there was no change at the "Processing text encoding ..." step.
CPU:i5-12400F   2.50 GHz
Graphic:RTX 3060TI 8G
Ram:16G

**Comment by Dravoss** [comment]
I have seen a few bug post like this, i have the same problem with a RTX and an AMD CPU, some times after a few minutes it does the first generation and goes smooth but after a few images it got stuck again.

**Comment by Dravoss** [comment]
I got it working using the linux install instructions from front page but adding this command at the end of the installation "python -m pip install --upgrade --force-reinstall --no-cache-dir --no-deps torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118" from issue https://github.com/lllyasviel/Fooocus/issues/113 so it works on windows. Maybe it is because doing this i got the last version of fooocus (1.0.45)

**Comment by Hoookah** [comment]
I solved this problem, it is the model file is corrupted, download these 2 model files separately

**Comment by Dravoss** [comment]
> I solved this problem, it is the model file is corrupted, download these 2 model files separately

Not in my case, i copy pasted my models from the non working windows installation to the linux guide manual installation and it worked.

**Comment by mashb1t** [comment]
If still renevant, please follow the official troubleshootijng guide here https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md
