### ISSUE TITLE
[Feature Request]: Ability to pause/resume generations

### ISSUE THREAD

**Issue by xx88xx** [lllyasviel/Fooocus#3415]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

<img width="229" alt="image" src="https://github.com/user-attachments/assets/4bb5007e-4199-43be-a693-fde56a5a4e36">

while a generation is running, would it be possible to perhaps add the option to pause generation (for example if you had set off a large batch and need to use your system resources for something important without stopping the entire batch. 

### Proposed workflow

After hitting generation,
a pause/resume button is shown under the "skip" button?
(perhaps if there is anything in the queue (from other fooocus instances running in other tabs) they start generating. (currently if a generation is stopped or finishes, other instances from the queue will start)

**Comment by mashb1t** [comment]
No, this is not feasible as everything would still have to be kept loaded in order to continue the generation. This would not be beneficial.

**Comment by xx88xx** [comment]
@mashb1t That makes total sense.

If that's the case, perhaps something like a "save current state as" could be beneficial? So sessions can be easily be re-populated and resumed or reused? Often when using image prompts or custom masks, this image data is not saved in the results. So it's very easy to lose track of what image prompts you were using when looking back at old generations.

Having something like an ability to repopulate fooocus with exactly what you had would potentially mean users can pause their generations and repopulate/resume their generations as needed without potential loss of data? and also as a result resolve the above.

Happy to create a new feature request if you think it's possible / workable

**Comment by mashb1t** [comment]
Your proposal makes a lot of sense, which is also why others already had the same idea ^^
see https://github.com/lllyasviel/Fooocus/issues/1622
The only issue is that if you reload the page users expect Fooocus to be reset to the preset, which has initially been st with `--preset foo`. Users also need the tabs to be resettable on misconfiguration to prevent getting stuck when accidentally changing values, e.g. in developer debug mode. Also parallel usage has to be kept in mind, you can use the URL / IP of your instance in multiple browsers and devices, which have to be independent (fyl in the beginning of Fooocus there was no separation, leading to user X seeing images of user Y and user Y of user Z, but not his own etc.).
You see, it's not easy.

What you can already do and which is already conform with separation and everything else mentioned above is to go to the history log, copy the metadata and then paste it in the prompt to apply all image parameters from metadata, not including image prompt due to file size).

I hope this helps to clarify the current situation.

**Comment by xx88xx** [comment]
@mashb1t thanks for the quick reply! the history log 'paste parameters' trick works great, has been super useful to use. I understand not being able to include image parameters in there natively, but would be it be possible to link to the images on our systems? so something like "C://pictures/example.png". So as long as the images haven't moved, it'll successfully link back up?

**Comment by mashb1t** [comment]
@xx88xx this has to be standardized and sometimes you also create a mask in inpainting for arn area, which will be put into the temp folder and which is not persistent. Furthermore you'd leak information when people copy the image to other computers and read the metadata there.

Solution would be:
- include image paths for image prompt
- not allow inpaint in metadata
- not allow enhance in metadata

But then again the people with more focus on privacy will complain that privacy information are leaking.

This outlines the difficult situation best i assume, so Fooocus is on a crossroad now: pivot more towards user-friendly, local inference with less privacy features OR use the business approach and be privacy compliant, but not as user-friendly.

**Comment by xx88xx** [comment]
@mashb1t perhaps we could have a tick box next to advanced that would allow lab like features that are more user friendly? (at the cost of loss of privacy) Then privacy focused users won’t be effected as its opt-in, but we can still have these more advanced user friendly features for those who want it
