### ISSUE TITLE
[Bug]: Plz fix A1111 Metadata scheme (with styles and Enhance)

### ISSUE THREAD

**Issue by Bra2ha** [lllyasviel/Fooocus#3425]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

If you use styles and try to save metadata using A1111 scheme it saves incorrectly.
Instead of: **Style3beg, Style2beg, Style1beg, Main prompt, Style1end, Style2end, Style3end**   
it saves like this:  **Style1beg, Main prompt, Style1end, Style2beg, Main prompt, Style2end, Style3beg, Main prompt, Style3end** 
also, if you have line breaks in prompt it saves like this:  **Style1beg, Line 1 of main prompt, Style1end, Style2beg, Line 2 of main prompt, Style2end, Style3beg, Line 3 of main prompt, Style3end** 
 
Also, if you use Enhance, instead of: 
**Style3beg, Style2beg, Style1beg, Main prompt, Style1end, Style2end, Style3end**
**Style3beg, Style2beg, Style1beg, Enhance 1 prompt, Style1end, Style2end, Style3end**
**Style3beg, Style2beg, Style1beg, Enhance 2 prompt, Style1end, Style2end, Style3end**
it saves only one last Enhance prompt (and same for negative)

### Steps to reproduce the problem

Write prompt, add styles, add Enhance prompt, generate, drag result to metadata window 

### What should have happened?

Described above

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### Console logs

```Shell
I can't find any info about prompt saving in console, except this:
[Fooocus] Saving image 1/1 to system ...
Image generated with private log at: e:\Fooocus_win64_2-5-0\Fooocus\outputs\2024-08-02\log.html

btw, in Log History in Raw prompt tab it also saves data incorrectly the same way as I described above.
```

### Additional information

If you have more than 2 spaces in a row in prompt and use Apply data it will ignore all text after those spaces.

**Comment by mashb1t** [comment]
## Styles in A1111 metadata

This is intended as it's the Fooocus way of using the prompt in general, which is exactly how it's applied in the SDXL generation process. If you generate an image with metadata scheme "fooocus" you'll also see this. Experience showed that using the main prompt multiple times results in SDXL better following it.

## Enhance

> it saves only one last Enhance prompt (and same for negative)

It's correct with the current implementation.
This is the prompt used to create the image, you can't reproduce it using metadata because the enhance information isn't saved in the image and it uses auto-generated masks, which might differ slightly each time they're automatically generated.

Excerpt of https://github.com/lllyasviel/Fooocus/discussions/3281:

> Upscaling or Variation
After Last Enhancement
choose which prompt to use for upscaling or variation, use either original prompts or last filled enhancement prompts with non-empty value (increases subject recognition, prevents subject from being changed back to original prompt after enhancement. Use this when substantially changing the subject described in the original prompts)

**Comment by Bra2ha** [comment]
Ok, I get it, but maybe you would be so kind as to add an option like "Export metadata for A1111/Forge/CivitAi" so that the user could automatically import a file with such metadata into A1111/Forge/CivitAi without having to manually copy and merge parts of the metadata?
