### ISSUE TITLE
Can't run it on Colab anymore

### ISSUE THREAD

**Issue by TransLingua** [lllyasviel/Fooocus#375]
It keeps running errors on Colab and shuts down

**Comment by lllyasviel** [comment]
i just tested and it seems still works..

**Comment by surroundsounnd** [comment]
I am also having this issue. I can create one set of images and then I receive errors and have to restart.

**Comment by gokuldaskumar** [comment]
Yes, the colab getting shutdown after the first image generation because of the high ram usage.

**Comment by lllyasviel** [comment]
I am looking into it

**Comment by lllyasviel** [comment]
In my test it wont crash for generating several images
but if you use it heavily, it will crash because the ram is not very stable
also, we do not know if Colab is intentionally influcing all SD/Gradio scripts ...
But I will try to fix in one or like two weeks by adding some more tricks
but Colab's hard disk is super slow, so like virtual memory is not a very good idea

**Comment by lllyasviel** [comment]
I fixed it in 2.0.16
I tested 2 hours with random image number and random prompt and random image size
it never crash
please test and see if problem is solved

**Comment by lllyasviel** [comment]
i think it is fixed
please reopen if needed

**Comment by TransLingua** [comment]
Thanks

**Comment by surroundsounnd** [comment]
Thank you very much!
