### ISSUE TITLE
Getting stuck on first run of launch.py

### ISSUE THREAD

**Issue by philsmy** [lllyasviel/Fooocus#39]
I am running this on an AWS EC2 g4dn instance (with GPU enabled) and Ubuntu 22.04 LTS

When I do `python launch.py --listen` it gets stuck at:

```
model_type EPS
adm 2560
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
```

I have done the 'simple' installation process from the readme and all seemed to go well.

Attaching the full output in a text file.
[launch-py--listen.txt](https://github.com/lllyasviel/Fooocus/files/12329039/launch-py--listen.txt)

I run InvokeAI on the same instance type/setup without issue.

**Comment by lllyasviel** [comment]
it seems ran out of system ram rather than vram - probably we need a bit optimization on this ..

**Comment by philsmy** [comment]
Yes. The instance has (only) 16GB of RAM. I added 4GB of swap and it got further, but now it has been sitting for 20 minutes at:

```
model_type EPS
adm 2560
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Refiner model loaded: sd_xl_refiner_1.0_0.9vae.safetensors
LoRAs loaded: [('sd_xl_offset_example-lora_1.0.safetensors', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5)]
```

**Comment by philsmy** [comment]
Machine has 16GB of ram. I added 4gb of swap and it is now running! I'm a little concerned that the memory was never released after the install though.

![Screen Shot 2023-08-14 at 0 07 04](https://github.com/lllyasviel/Fooocus/assets/16431/c2597a36-78bd-4890-9db8-5bcb01e24989)

**Comment by philsmy** [comment]
Sadly it is not usable. I do get the UI up and can enter a prompt but it starts to process then everything seems to freeze. Also, I see no movement on the GPU usage chart.

**Comment by lllyasviel** [comment]
yes we may confirm that this is low ram problem.
this is because both xl base and refiner are used for best results.
if invokeai can work on this machine, then does invokeai use both base and refiner?
if they are not loading less models then i can probably take a look at other methods for system ram optimization

**Comment by philsmy** [comment]
You're quite right. SDXL under InvokeAI doesn't run either. I will get a bigger instance tomorrow and go through it again.

**Comment by lllyasviel** [comment]
The test passed on my end with 8GB RAM on windows. see also updated readme installation guides with images and explanations.
But I am not sure if linux can do that

**Comment by elbowdonkey** [comment]
I'm using a Proxmox cluster to try and run Fooocus on a Ubuntu VM. I pass through a RTX3060 with 12GB to that VM. The host machine has 192GB of RAM, with 64GB allocated to the VM.

This VM runs SDXL on InvokeAI, Auto111, ComfyUI, without issue.

When running `python launch.py --listen`, the process is eventually killed. I can paste all the messages seen after executing the launch script, but ultimately there's no error - it just ends with:

```
building MemoryEfficientAttnBlock with 512 in_channels...
Killed
```

I'm not quite sure if this is a RAM issue or what. Typically when I've seen `Killed` it's because of too little ram. That said, not sure why other SDXL compatible projects load the SDXL models without issue.

**Comment by igorw765** [comment]
I'm also getting:
`building MemoryEfficientAttnBlock with 512 in_channels...
[1]    3299 killed     python launch.py`

OS: Arch Linux
CPU: i5-9600k
GPU: GTX 750 ti
RAM; 24GB DDR4
Swap: 4GB
