### ISSUE TITLE
[Feature Request] Output final prompt to console and private generation log

### ISSUE THREAD

**Issue by ikarsokolov** [lllyasviel/Fooocus#517]
As far as I'm aware, Fooocus currently doesn't display the final prompt (after resolving style templates) in either the standard output or the generated images log. The only output I could find is from the `Fooocus V2` expansion model.

It would be immensely helpful to have the complete prompt used for inference available for further customization or for reproducing the generated image.

I'm particularly interested in understanding how Fooocus combines multiple selected styles.

**Comment by lllyasviel** [comment]
Fooocus uses its own special algorithm to process styles.

Getting “raw” prompts from Fooocus is impossible because Fooocus style mixture has nothing to do with text. All processing is directly inside deep neural network features.

This may bring some inconvenience for a small group of users but we put result quality in the first place, so we are unlikely to change this design unless some other algorithms are reported to outperform the result quality of Fooocus.

**Comment by lllyasviel** [comment]
style template are text based.
style mixture has nothing to do with text.
Not to confuse these two.
And all template references works as most expected way
