### ISSUE TITLE
1660Super & 16gbRAM RuntimeError-not enough memory

### ISSUE THREAD

**Issue by Tomdoog** [lllyasviel/Fooocus#64]
![O MZE(5)CQMEYC~4A$A3KSL](https://github.com/lllyasviel/Fooocus/assets/28556445/a3abf479-0755-453b-960c-2a45f52c8929)
![SI NX116 F@)84{0UR3D }S](https://github.com/lllyasviel/Fooocus/assets/28556445/a11fba02-0054-410d-bb42-655b06b9add2)

**Comment by igstranger** [comment]
I have the same hardware as you and similar problems
![image](https://github.com/lllyasviel/Fooocus/assets/19337508/b5c87e5d-9af1-442d-9e4b-e03f2b9ca138)

**Comment by birbitci** [comment]
### ****s

**Comment by mitchellkrogza** [comment]
I have a 12gb RTX 3060 and 16gb of ram and this just kills my Linux machine. Tried 3 times with htop open in the background and could now and then see (between freezes) python using 32gb+ and Chrome using 32gb+ and hard drive light solid from it thrashing swap

**Comment by mitchellkrogza** [comment]
> Hi users, For the windows reports about, the problem is probably caused by the device does not support float16 so that the VRAM is not effectively used. This may not be flexibly solved, but we will find some solutions soon.
> 
> For the Linux report about, the problem is probably because the swap area on your disk is not large enough – this seems possible to solve with system configuration editing.
> 
> We tested linux with standard free T4 GPU and 16G system RAM in standard google colab devices, and it seems work without problem. See also the colab in the README and see if your system needs more configurations about system ram.

I got this working yesterday with out my 64 GB RAM kit due to arrive today. Simply had Chrome and Thunderbird closed (both memory hungry beasts) opened Fooocus in a single tab in Chromium and works 100% takes several minutes to render but the results were outstanding compared to the poor results from Automatic1111. I must commend you @lllyasviel you have made a fantastic tool here. I can't wait to play more and look forward to more features. Well done 👍🏻
![image1](https://github.com/lllyasviel/Fooocus/assets/9961541/1a70b5c6-6ef4-4a0d-8c11-fc023ccd41d2)
