### ISSUE TITLE
Stuck on loading model

### ISSUE THREAD

**Issue by fabwaseem** [lllyasviel/Fooocus#745]
Foocus is stuck on loading the model for hours while eating all my 16gb ram and disk usage with no sign of any response in either the UI or the terminal.
It was working perfectly just two days ago and faced this problem yesterday, even deleted the old ones and downloaded new but with the same result please help me.
![Screenshot 2023-10-20 143931](https://github.com/lllyasviel/Fooocus/assets/66861984/42d8ffcd-5474-4832-9225-69d575dab8fb)

**Comment by lllyasviel** [comment]
if `It was working perfectly just two days ago and faced this problem yesterday` then it means you are using SSD and HDD at the same time, and two days ago your SSD has enough free space, but today your SSD is full and your PC has to use HDD as processing/caching unit, causing slow down and crash

**Comment by fabwaseem** [comment]
yes, I'm using SSD and HDD, and freed almost 90gb now in my SSD but still the same problem. What is the minimum requirement for fooocus?

**Comment by lllyasviel** [comment]
if you just freeed space but Windows is still not using SSD, then perhaps you need to restart computer.
otherwise, you can try to manually set up swap file setting to force Windows always use SSD as memory swap, though this can be dangerous. this can be done by changing the step 7 of the image instrucion in the readme (see that "Click here to the see the image instruction" in the readme) note that this also requires restart

**Comment by fabwaseem** [comment]
yeah this worked, thank you so much
