### ISSUE TITLE
Is there a third option for Speed,Quality in Performance, such as faster

### ISSUE THREAD

**Issue by tiancool** [lllyasviel/Fooocus#813]
The way I work is to quickly find a suitable picture from multiple groups of pictures and regenerate it into a high-quality final picture. At present, Speed is still too slow to make a batch selection.
Speed: Steps = 30 - 20, change to 10?

**Comment by lllyasviel** [comment]
`quickly find a suitable picture` should use the `skip` button

but yes you can go to `developer tools` to force overwrite steps. but keep in mide that the step in fooocus is different from webui/comfyui since we use special quality improvement on exact step numbers like 30, and this also influences the sd15-as-refiner improvements.
