### ISSUE TITLE
GPT(fooocus v2) seems to have undesirable influence to styles. Is it what GPT enhancement was designed to do?

### ISSUE THREAD

**Issue by lanyusan** [lllyasviel/Fooocus#828]
When I chose SAI line art only, Fooocus generated excellent line art. When I chose both SAI line art and fooocus v2, the output was close to realistic style. 

Is it intended? I thought GPT was style neurtral.

SAI line art only:
![Screenshot from 2023-11-01 09-54-05](https://github.com/lllyasviel/Fooocus/assets/56706512/21f6ed0a-f854-4cf3-9513-47a1a4003abe)

SAI line art and fooocus v2:

![Screenshot from 2023-11-01 09-52-33](https://github.com/lllyasviel/Fooocus/assets/56706512/ebf86d0e-eef1-4fdd-87b8-5bd9e7ca5a86)

**Comment by lllyasviel** [comment]
This is why we put "Fooocus V2" inside "styles" - because it is a style, and of course it will influence the image style. 

Some forks put it outside "Style" Tab and mislead people into believing it wont influence style - not our problem.

Also you can prompt line drawing
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/96ec9fa5-9479-43cc-ac6c-0f221f4df9ab)

**Comment by lanyusan** [comment]
Thanks for the clarification. I thought it was semantic enhancement only.
